MPGS-1295 #comment Add basic content to the created files
Medialem/flask-platform-reviewofpurchase pull request #1
Opened 2020-12-29 15:02 UTC by medea-learner

2020-12-29 15:59 UTC, hzerdia commented on flask_platform_reviewofpurchase/models.py
> +
Where is the relationship with the purchase ?

2020-12-29 15:59 UTC, hzerdia commented on flask_platform_reviewofpurchase/adminviews.py
> +    unified_form = ReviewOfPurchaseForm
I don't see the definition of the ReviewOfPurchaseForm

2020-12-30 14:22 UTC, hzerdia commented on flask_platform_reviewofpurchaseitem/forms.py
> +        if request.method == 'POST' and self.purchase_item.data and self.purchase_item.data.user.id == user.id:
purchase item does not have a user relationship check the PurchaseItem model

2021-01-03 11:59 UTC, fchennouf requested changes

2021-01-03 11:59 UTC, fchennouf commented on flask_platform_reviewofpurchaseitem/forms.py
> +        if request.method == 'POST':
do not use this, use is_update function.

2021-01-03 11:59 UTC, fchennouf commented on flask_platform_reviewofpurchaseitem/forms.py
> +            if current_user.has_role('admin'):
who said this ? admin can do whatever he wants.

2021-01-03 11:59 UTC, fchennouf commented on flask_platform_reviewofpurchaseitem/forms.py
> +            del self.user
:medal_military:

2021-01-03 11:59 UTC, fchennouf commented on flask_platform_reviewofpurchaseitem/forms.py
> +            # Other than the buyer can't review this purchase item
remove this part

2021-01-03 11:59 UTC, fchennouf commented on flask_platform_reviewofpurchaseitem/forms.py
> +            if ReviewOfPurchaseItem.get_by_identifier(purchase_item=self.purchase_item.data, user=user):
be careful, this raise an exception if no element. use filter function of sqlalchemy.

2021-01-03 11:59 UTC, fchennouf commented on flask_platform_reviewofpurchaseitem/forms.py
> +                    self.purchase_item.errors = self.purchase_item.errors + (str(lazy_gettext('You have already reviewed this purchase item')),)
use  self.purchase_item.errors.append()

2021-01-03 12:04 UTC, fchennouf requested changes

2021-01-03 12:04 UTC, fchennouf commented on flask_platform_reviewofpurchaseitem/models.py
> +    purchase_item_id = db.Column(db.Integer, db.ForeignKey("psi_purchase_item.psi_id"), nullable=False)
do not forget column name as first param.

2021-01-03 12:06 UTC, fchennouf requested changes

2021-01-03 12:06 UTC, fchennouf commented on Flask_Platform_Reviewofpurchase.egg-info/PKG-INFO
> +Classifier: Topic :: Software Development :: Libraries :: Python Modules
why do you track theses files ? inside .egg-info/

2021-01-03 12:06 UTC, fchennouf commented on Flask_Platform_Reviewofpurchase.egg-info/SOURCES.txt
> +flask_platform_reviewofpurchaseitem/views.py
why do you track theses files ? inside .egg-info/

2021-01-03 12:06 UTC, fchennouf commented on Flask_Platform_Reviewofpurchase.egg-info/not-zip-safe
> +
why do you track theses files ? inside .egg-info/

2021-01-03 12:06 UTC, fchennouf commented on Flask_Platform_Reviewofpurchase.egg-info/requires.txt
> +Flask-Platform-Purchase@ git+ssh://git@github.com/Medialem/flask-platform-purchase.git@vdevelop#egg=flask-platform-purchase
why do you track theses files ? inside .egg-info/

2021-01-03 12:06 UTC, fchennouf commented on Flask_Platform_Reviewofpurchase.egg-info/top_level.txt
> +flask_platform_reviewofpurchaseitem
why do you track theses files ? inside .egg-info/

2021-01-03 12:06 UTC, fchennouf commented on Flask_Platform_Reviewofpurchase.egg-info/dependency_links.txt
> +
why do you track theses files ? inside .egg-info/

2021-01-03 12:13 UTC, medea-learner commented on flask_platform_reviewofpurchaseitem/models.py
> +    purchase_item = db.relationship(PurchaseItem, backref=db.backref("rop_reviews_of_purchase_item", uselist=False))
I tried the other way, but it didn't work

2021-01-03 12:32 UTC, medea-learner commented on flask_platform_reviewofpurchaseitem/forms.py
> +            # Other than the buyer can't review this purchase item
why I remove this part?

2021-01-03 13:11 UTC, medea-learner commented on flask_platform_reviewofpurchaseitem/forms.py
> +                    self.purchase_item.errors = self.purchase_item.errors + (str(lazy_gettext('You have already reviewed this purchase item')),)
we cannot replace it because, it is a tuple and append doesn't work with tuples

2021-01-03 13:42 UTC, medea-learner commented on flask_platform_reviewofpurchaseitem/forms.py
> +            if current_user.has_role('admin'):
He cannot create reviews for other people
He can update, delete, create(his own purchase item's review)
what d y think?

2021-01-03 13:43 UTC, medea-learner commented on flask_platform_reviewofpurchaseitem/forms.py
> +        if request.method == 'POST':
I don't understand

2021-01-03 15:05 UTC, medea-learner commented on flask_platform_reviewofpurchaseitem/forms.py
> +            if ReviewOfPurchaseItem.get_by_identifier(purchase_item=self.purchase_item.data, user=user):
def get_by_identifier(cls, **kwargs):
        try:
            return cls.query.filter_by(**kwargs).one()
        except NoResultFound:
            return None
        except MultipleResultsFound:
            return None
There will be no exception to raise, all cases are treated

2021-01-03 19:09 UTC, fchennouf commented on flask_platform_reviewofpurchaseitem/forms.py
> +        if request.method == 'POST':
do not use request.method == 'POST to check if you are in creation or update, use is_update function.

2021-01-03 19:10 UTC, fchennouf commented on flask_platform_reviewofpurchaseitem/forms.py
> +            if current_user.has_role('admin'):
the admin can generally do whatever he wants, do not limitate its actions unless it's explicitely asked.

2021-01-03 19:12 UTC, fchennouf commented on flask_platform_reviewofpurchaseitem/forms.py
> +            if ReviewOfPurchaseItem.get_by_identifier(purchase_item=self.purchase_item.data, user=user):
you're right, but use filter anyway, it's more explicit. this function will no doubt be depracted in the futur.

2021-01-03 19:14 UTC, fchennouf commented on flask_platform_reviewofpurchaseitem/forms.py
> +                    self.purchase_item.errors = self.purchase_item.errors + (str(lazy_gettext('You have already reviewed this purchase item')),)
the problem i think is that you are not validating the field that's why you are having a tuple instead of an array. Errors should be an array. check it again.

2021-01-03 19:16 UTC, fchennouf commented on flask_platform_reviewofpurchaseitem/forms.py
> +                    self.purchase_item.errors = self.purchase_item.errors + (str(lazy_gettext('You have already reviewed this purchase item')),)
wether move super(ReviewOfPurchaseItemForm, self).validate() at the beginning of your code, or use self.purchase_item.validate() (check with fields in wtforms, i dont remember exactly the function signature)

2021-01-03 19:18 UTC, fchennouf commented on flask_platform_reviewofpurchaseitem/forms.py
> +                    self.purchase_item.errors = self.purchase_item.errors + (str(lazy_gettext('You have already reviewed this purchase item')),)
check forms inside product module to get an idea.

2021-01-03 19:20 UTC, fchennouf commented on flask_platform_reviewofpurchaseitem/models.py
> +    purchase_item = db.relationship(PurchaseItem, backref=db.backref("rop_reviews_of_purchase_item", uselist=False))
this should work with autogenerate, check it again. use one_to_one.

2021-01-03 19:21 UTC, fchennouf commented on flask_platform_reviewofpurchaseitem/models.py
> +    purchase_item = db.relationship(PurchaseItem, backref=db.backref("rop_reviews_of_purchase_item", uselist=False))
take a look at Cart model in purchase module

2021-01-04 10:53 UTC, fchennouf approved these changes

2021-01-04 10:53 UTC, fchennouf commented on flask_platform_reviewofpurchaseitem/configs.py
> +        'REVIEW_OF_PURCHASE_ITEM_REQUIRED_FIELDS': [],
this variable is not used and should be removed

2021-01-04 10:53 UTC, fchennouf commented on flask_platform_reviewofpurchaseitem/forms.py
> +        if db.session.query(ReviewOfPurchaseItem).filter(ReviewOfPurchaseItem.purchase_item==self.purchase_item.data, ReviewOfPurchaseItem.user==user).first():
```suggestion
        if ReviewOfPurchaseItem.query.filter(ReviewOfPurchaseItem.purchase_item==self.purchase_item.data).first():
```
You do not need to specifiy the user as only one review can be done per purchase item.

2021-01-04 10:53 UTC, fchennouf commented on flask_platform_reviewofpurchaseitem/forms.py
> +        # The buyer can't review more than once this purchase item
```suggestion
        # The purchase item can't be reviewed more than once.
```

2021-01-04 10:53 UTC, fchennouf commented on flask_platform_reviewofpurchaseitem/forms.py
> +            self.purchase_item.errors.append(str(lazy_gettext('You have already reviewed this purchase item')),)
```suggestion
            self.purchase_item.errors.append(gettext('You have already reviewed this purchase item'))
```

2021-01-04 10:53 UTC, fchennouf commented on setup.py
>      author_email='',
name='Flask-Platform-ReviewOfPurchaseItem',

2021-01-04 12:35 UTC, merged